#!/bin/sh

#----------------------------------------------------------
# OVS project
# run this script after rebooting computer or network
#----------------------------------------------------------

#load ovs kernel module
modprobe openvswitch

#start database server
ovsdb-server \
--remote=punix:/usr/local/var/run/openvswitch/db.sock \
--remote=db:Open_vSwitch,Open_vSwitch,manager_options \
--pidfile \
--detach \
--log-file

#start ovs demon
ovs-vswitchd --pidfile --detach

#destroy default virsh interface
virsh net-destroy default

#start ovsdb-server
ovsdb-server \
--remote=punix:/usr/local/var/run/openvswitch/db.sock \
--remote=db:Open_vSwitch,Open_vSwitch,manager_options \
--pidfile \
--detach \
--log-file

#start ovs demon
sudo ovs-vswitchd --pidfile --detach

#zero out eth1 interface
ifconfig eth1 0

#add bridge 
ovs-vsctl add-br br1

#add eth interface to the ovs bridge
ovs-vsctl add-port br1 eth1
dhclient br1

#print out some results
ovs-vsctl show
ifconfig -a





