#!/bin/sh

#restart ovs after rebooting host
#sudo or root should be used

#load and verify kernel module
modprobe openvswitch
lsmod | grep openvswitch

#start ovsdb server
ovsdb-server \
--remote=punix:/usr/local/var/run/openvswitch/db.sock \
--remote=db:Open_vSwitch,Open_vSwitch,manager_options \
--pidfile \
--detach \
--log-file

#start ovs demon
ovs-vswitchd --pidfile --detach

#verify OVS modules
lsmod | grep br

