#!/bin/sh

# kernel module debugging

#---------------------------------------------------------------------------------
#ftrace
sudo su
cd /sys/kernel/debug/tracing

# turn tracing off and verify it
	echo 0 > tracing_on
	cat tracing_on
#to see available tracers
	cat available_tracers
#set tracer type(s) and verify it (them)
	echo function_graph > current_tracer
	cat current_tracer
#we might want to clear filter before setting it and verify results
	echo > set_ftrace_filter
	cat set_ftrace_filter
#to disable some funcitons, for example spin_lock(...) use this
	echo spin_lock > set_ftrace_notrace
	cat set_ftrace_notrace
#to clear disabled functions list use
	echo > set_ftrace_notrace
	cat set_ftrace_notrace
#to trace particular function for example dp_init(...)
	echo dp_init > set_ftrace_filter
	cat set_ftrace_filter
#or for all functions in module   
	echo :mod:openvswitch > set_ftrace_filter
	cat set_ftrace_filter
#turn on and start tracing
	echo 1 > tracing_on
#to get trace in real time
	cat trace_pipe
#or
	cat trace
#to list available filter functions (can be used with grep to set filter functions with wildcards"
	wc -l  available_filter_functions
#to enable filter functions directly using wildcard
	echo 'set*' > set_ftrace_filter
	cat set_ftrace_filter | head -5

#to see messages printed by pr_info
	cat /dev/kmsg

#to install kernelshark
	sudo apt-get install kernelshark
	sudo apt-get install trace-cmd
#to extract kernel trace in file trace.data and see it in kernelshark
	trace-cmd extract
	kernelshark

# ??
	cat /proc/kmsg 
	dmesg
	echo 8 > /proc/sys/kernel/printk



