#!/bin/bash

############################
#this scripts find files with the extention given by first argument 
#default is "*.lrp2" 
#and copy them to the files with the extention given by second argument
#default is ".lrp" 
############################

fnum=0

extsrc=$1
if [ -z "$extsrc" ]; then extsrc="*.lrp2"
fi

extdst=$2
if [ -z "$extdst" ]; then extdst=".lrp"
fi

for file in $(find . -iname "*$extsrc" )
do
let "fnum += 1"
cp -f $file ${file%$extsrc}$extdst
done

echo "processed files : " $fnum
