#!/bin/bash

#------------------------------------------------
# global variables
#------------------------------------------------

MODE=$1
DATE=2010/9/20
USER=vladn
lnum=0
pnum=0
nnum=0
fnum=0
tnum=0
tnump=0

if [ -n "$2" ]; then USER=$2
fi
if [ -n "$3" ]; then DATE=$3
fi

#-------------------------------------------------
# support functions
#-------------------------------------------------

# print to stdout mode value
function mode_msg
{
	echo "USER: " $USER
	echo "DATE: " $DATE
	if [ -z "$MODE" ]; then echo "mode: HELP"
	else echo "mode: $MODE"
	fi
}

# print help message
function help_msg
{
 	echo " script for the printing information about changed lines in the CVS project"
        echo " version vn-061128-1406"
	echo " usage: "
	echo " $0 mode [USER [DATE]]"
	echo " check out all changed checked in later or on DATE"
	echo "            default USER = vladn"
	echo "            default DATE = $DATE"
	echo " modes"
	echo "     1 : prints out info for all files found"
	echo "     2 : print only numbers for all files found"
	echo "     3 : count and print changed lines summary"
	echo "     4 : count and print changed lines summary and extended info"
	echo "     5 : get all changes in the files in the CVS made by others but me USER"
	echo "     6 : get all changes in the files in the CVS with file name and autor"
}

# print to stdout values of global variables
function debug_msg
{
    echo "debug_msg"
    echo "file: " $file
    echo "pnum: " $pnum
    echo "nnum: " $nnum
}

function get_info1
{
    cvs log -NS -w$USER -d ">$DATE" | grep -e 'Working file.*' -e 'lines.*'
}

function get_info2
{
    cvs log -NS -w$USER -d ">$DATE" | grep  -o '[\+\-][0-9][0-9]*'
}

# count all added and removed lines in all filed modified in the down tree
function get_info3 
{
    for file in $(find . -iname "*.[ch]" -o -iname "*.[ch]pp")
      do
      let "fnum += 1"
      cnum=$(cvs log -lNS -w$USER -d ">$DATE" $file | grep -o '\+[0-9][0-9]*')
      if [ "$cnum" ]; then let "pnum += $cnum"
      fi
      cnum=$(cvs log -lNS -w$USER -d ">$DATE" $file | grep -o '\-[0-9][0-9]*')
      if [ "$cnum" ]; then let "nnum += -$cnum"
      fi

      let "lnum += $(wc -l $file | head -c 8)"
      #debug_msg
    done

    let "tnum  = $pnum + $nnum"
    let "tnump = ($tnum * 100) / $lnum"

}

function print_info3
{
    echo "total lines changed: " $tnum  # "(" $tnump "% )"
}

function print_info3_extended
{
    echo "source files *.c *.h *.cpp *.hpp :"
    echo "files tested:        " $fnum
    echo "number of lines:     " $lnum
    echo "new lined added:     " $pnum
    echo "old lines removed:   " $nnum
    echo "total lines changed: " $tnum   "(" $tnump "% )"
}

# get all changes in the files in the CVS made by others but me (vladn)
function get_info5
{
    cvs log -d ">$DATE" | grep author | grep -v "$USER" 
}

function get_info6
{
    cvs log -N -d ">$DATE" | grep author -B 10 | grep -e date -e Working
}


#-----------------------------------------------------------
# main processing
#-----------------------------------------------------------

# execute commands given by mode
mode_msg
case "$MODE" in
"") 	# print help message
	help_msg
	;;
"1")	# 
        get_info1
	;;
"2")	# 
        get_info2
	;;
"3")	#
        get_info3
	print_info3
	;;
"4")	#
        get_info3
	print_info3_extended
	;;
"5")	#
        get_info5
	;;
"6")	#
        get_info6
	;;
esac

