#!/bin/bash
rm -f rm.csv
#grep s3r3 out-txt-rm.csv > rm.csv

#grep "s3r3i[0-9]\{4\}" out-txt-rm.csv > rm.csv

#r 7 - 13
#i 100 - 130
grep "s3r[0-3][0-9]i00[0-1][0-9]\b" out-txt-rm.csv > rm.csv

ls -lh rm.csv