#!/bin/bash

############################
# mico - Microcode Converter
# this scripts find files using pattern given by the first argument, 
# default is *.lrp2 #pattern must be given in the quota marks like '*.txt'
# 1. replaces in these files define with @define
# 2. replaces om these files @include aaa with @include "aaa"
############################

fnum=0
patsrc=$1
if [ -z "$patsrc" ]; then patsrc="*.lrp2"
fi

for file in $(find . -iname "$patsrc" )
do
let "fnum += 1"
tmp="$file"__
rm -f $tmp
sed -e 's/\(@include\)[ \t]\+\([^\"][a-zA-Z0-9_\.\/]\+\)/\1 \"\2\"/g' -e 's/\([^@]\)\(define\)/\1@\2/g' -e 's/^\(define\)/@\1/g' $file > $tmp
mv -f $tmp $file
done

echo "number of processed files : " $fnum
