.TH "/home/vladn/git/ovs/datapath/linux/compat/include Directory Reference" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBlinux\fP"
.br
.ti -1c
.RI "directory \fBnet\fP"
.br
.in -1c
