.TH "action_fifo" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
action_fifo \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBhead\fP"
.br
.ti -1c
.RI "int \fBtail\fP"
.br
.ti -1c
.RI "struct \fBdeferred_action\fP \fBfifo\fP [\fBDEFERRED_ACTION_FIFO_SIZE\fP]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBdeferred_action\fP action_fifo::fifo"

.SS "int action_fifo::head"

.SS "int action_fifo::tail"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
