.TH "arp_eth_header" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
arp_eth_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be16 \fBar_hrd\fP"
.br
.ti -1c
.RI "__be16 \fBar_pro\fP"
.br
.ti -1c
.RI "unsigned char \fBar_hln\fP"
.br
.ti -1c
.RI "unsigned char \fBar_pln\fP"
.br
.ti -1c
.RI "__be16 \fBar_op\fP"
.br
.ti -1c
.RI "unsigned char \fBar_sha\fP [ETH_ALEN]"
.br
.ti -1c
.RI "unsigned char \fBar_sip\fP [4]"
.br
.ti -1c
.RI "unsigned char \fBar_tha\fP [ETH_ALEN]"
.br
.ti -1c
.RI "unsigned char \fBar_tip\fP [4]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "unsigned char arp_eth_header::ar_hln"

.SS "__be16 arp_eth_header::ar_hrd"

.SS "__be16 arp_eth_header::ar_op"

.SS "unsigned char arp_eth_header::ar_pln"

.SS "__be16 arp_eth_header::ar_pro"

.SS "unsigned char arp_eth_header::ar_sha[ETH_ALEN]"

.SS "unsigned char arp_eth_header::ar_sip[4]"

.SS "unsigned char arp_eth_header::ar_tha[ETH_ALEN]"

.SS "unsigned char arp_eth_header::ar_tip[4]"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
