.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/sctp/checksum.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/sctp/checksum.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static __le32 \fBsctp_compute_cksum\fP (const struct sk_buff *skb, unsigned int offset)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static __le32 sctp_compute_cksum (const struct sk_buff * skb, unsigned int offset)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
9 {
10     const struct sk_buff *iter;
11 
12     __u32 crc32 = sctp_start_cksum(skb->data + offset,
13                        skb_headlen(skb) - offset);
14     skb_walk_frags(skb, iter)
15         crc32 = sctp_update_cksum((__u8 *) iter->data,
16                       skb_headlen(iter), crc32);
17 
18     /* Open-code sctp_end_cksum() to avoid a sparse warning due to a bug in
19      * sparse annotations in Linux fixed in 3\&.10 in commit eee1d5a14 (sctp:
20      * Correct type and usage of sctp_end_cksum())\&. */
21     return cpu_to_le32(~crc32);
22 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
