.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/compiler-gcc.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/compiler-gcc.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__packed\fP   \fB__attribute__\fP((packed))"
.br
.ti -1c
.RI "#define \fB__always_unused\fP   \fB__attribute__\fP((unused))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __always_unused   \fB__attribute__\fP((unused))"

.SS "#define __packed   \fB__attribute__\fP((packed))"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
