.TH "deferred_action" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deferred_action \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct sk_buff * \fBskb\fP"
.br
.ti -1c
.RI "const struct nlattr * \fBactions\fP"
.br
.ti -1c
.RI "struct \fBsw_flow_key\fP \fBpkt_key\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "const struct nlattr * deferred_action::actions"

.SS "struct \fBsw_flow_key\fP deferred_action::pkt_key"

.SS "struct sk_buff * deferred_action::skb"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
