.TH "/home/vladn/git/ovs/datapath/linux/dev-openvswitch.c" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/dev-openvswitch.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/if_bridge\&.h>\fP
.br
\fC#include <linux/netdevice\&.h>\fP
.br
\fC#include <linux/version\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdev_disable_lro\fP (struct net_device *dev)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void dev_disable_lro (struct net_device * dev)"

.PP
.nf
31 { }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
