.TH "dp_stats_percpu" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dp_stats_percpu \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datapath\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u64 \fBn_hit\fP"
.br
.ti -1c
.RI "u64 \fBn_missed\fP"
.br
.ti -1c
.RI "u64 \fBn_lost\fP"
.br
.ti -1c
.RI "u64 \fBn_mask_hit\fP"
.br
.ti -1c
.RI "struct \fBu64_stats_sync\fP \fBsyncp\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBdp_stats_percpu\fP - per-cpu packet processing statistics for a given datapath\&. : Number of received packets for which a matching flow was found in the flow table\&. : Number of received packets that had no matching flow in the flow table\&. The sum of  and  is the number of packets that have been received by the datapath\&. : Number of received packets that had no matching flow in the flow table that could not be sent to userspace (normally due to an overflow in one of the datapath's queues)\&. : Number of masks looked up for flow match\&.  / ( + ) will be the average masks looked up per packet\&. 
.SH "Field Documentation"
.PP 
.SS "u64 dp_stats_percpu::n_hit"

.SS "u64 dp_stats_percpu::n_lost"

.SS "u64 dp_stats_percpu::n_mask_hit"

.SS "u64 dp_stats_percpu::n_missed"

.SS "struct \fBu64_stats_sync\fP dp_stats_percpu::syncp"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
