.TH "dp_upcall_info" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
dp_upcall_info \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <datapath\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "const struct \fBovs_tunnel_info\fP * \fBegress_tun_info\fP"
.br
.ti -1c
.RI "const struct nlattr * \fBuserdata\fP"
.br
.ti -1c
.RI "const struct nlattr * \fBactions\fP"
.br
.ti -1c
.RI "int \fBactions_len\fP"
.br
.ti -1c
.RI "u32 \fBportid\fP"
.br
.ti -1c
.RI "u8 \fBcmd\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct dp_upcall - metadata to include with a packet to send to userspace : One of OVS_PACKET_CMD_*\&. : If nonnull, its variable-length value is passed to userspace as OVS_PACKET_ATTR_USERDATA\&. : Netlink portid to which packet should be sent\&. If  is 0 then no packet is sent and the packet is accounted in the datapath's  counter\&. : If nonnull, becomes OVS_PACKET_ATTR_EGRESS_TUN_KEY\&. 
.SH "Field Documentation"
.PP 
.SS "const struct nlattr* dp_upcall_info::actions"

.SS "int dp_upcall_info::actions_len"

.SS "u8 dp_upcall_info::cmd"

.SS "const struct \fBovs_tunnel_info\fP* dp_upcall_info::egress_tun_info"

.SS "u32 dp_upcall_info::portid"

.SS "const struct nlattr* dp_upcall_info::userdata"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
