.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/etherdevice.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/etherdevice.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/version\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBether_addr_copy\fP (u8 *\fBdst\fP, const u8 *\fBsrc\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void ether_addr_copy (u8 * dst, const u8 * src)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
39 {
40 #if defined(CONFIG_HAVE_EFFICIENT_UNALIGNED_ACCESS)
41     *(u32 *)dst = *(const u32 *)src;
42     *(u16 *)(dst + 4) = *(const u16 *)(src + 4);
43 #else
44     u16 *a = (u16 *)dst;
45     const u16 *b = (const u16 *)src;
46 
47     a[0] = b[0];
48     a[1] = b[1];
49     a[2] = b[2];
50 #endif
51 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
