.TH "geneve_port" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
geneve_port \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct geneve_sock * \fBgs\fP"
.br
.ti -1c
.RI "char \fBname\fP [IFNAMSIZ]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct geneve_sock * geneve_port::gs"

.SS "char geneve_port::name"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
