.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/gre.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/gre.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/skbuff\&.h>\fP
.br
\fC#include <net/ip_tunnels\&.h>\fP
.br
\fC#include <linux/version\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBgre_cisco_protocol\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMAX_GRE_PROTO_PRIORITY\fP   255"
.br
.ti -1c
.RI "#define \fBgre_cisco_register\fP   \fBrpl_gre_cisco_register\fP"
.br
.ti -1c
.RI "#define \fBgre_cisco_unregister\fP   \fBrpl_gre_cisco_unregister\fP"
.br
.ti -1c
.RI "#define \fBgre_handle_offloads\fP   \fBrpl_gre_handle_offloads\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBrpl_gre_cisco_register\fP (struct \fBgre_cisco_protocol\fP *\fBproto\fP)"
.br
.ti -1c
.RI "int \fBrpl_gre_cisco_unregister\fP (struct \fBgre_cisco_protocol\fP *\fBproto\fP)"
.br
.ti -1c
.RI "struct sk_buff * \fBrpl_gre_handle_offloads\fP (struct sk_buff *skb, \fBbool\fP gre_csum)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define gre_cisco_register   \fBrpl_gre_cisco_register\fP"

.SS "#define gre_cisco_unregister   \fBrpl_gre_cisco_unregister\fP"

.SS "#define gre_handle_offloads   \fBrpl_gre_handle_offloads\fP"

.SS "#define MAX_GRE_PROTO_PRIORITY   255"

.SH "Function Documentation"
.PP 
.SS "int rpl_gre_cisco_register (struct \fBgre_cisco_protocol\fP * proto)"

.SS "int rpl_gre_cisco_unregister (struct \fBgre_cisco_protocol\fP * proto)"

.SS "struct sk_buff* rpl_gre_handle_offloads (struct sk_buff * skb, \fBbool\fP gre_csum)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
