.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/icmpv6.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/icmpv6.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "static struct icmp6hdr * \fBicmp6_hdr\fP (const struct sk_buff *skb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static struct icmp6hdr* icmp6_hdr (const struct sk_buff * skb)\fC [static]\fP"

.PP
.nf
8 {
9     return (struct icmp6hdr *)skb_transport_header(skb);
10 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
