.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/if_arp.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/if_arp.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/skbuff\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static struct arphdr * \fBarp_hdr\fP (const struct sk_buff *skb)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static struct arphdr* arp_hdr (const struct sk_buff * skb)\fC [static]\fP"

.PP
.nf
10 {
11     return (struct arphdr *)skb_network_header(skb);
12 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
