.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/if_ether.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/if_ether.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBETH_P_802_3_MIN\fP   0x0600"
.br
.ti -1c
.RI "#define \fBETH_P_8021AD\fP   0x88A8          /* 802\&.1ad Service VLAN         */"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ETH_P_8021AD   0x88A8          /* 802\&.1ad Service VLAN         */"

.SS "#define ETH_P_802_3_MIN   0x0600"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
