.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/in.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/in.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/module\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBbool\fP \fBipv4_is_loopback\fP (__be32 \fBaddr\fP)"
.br
.ti -1c
.RI "static \fBbool\fP \fBipv4_is_multicast\fP (__be32 \fBaddr\fP)"
.br
.ti -1c
.RI "static \fBbool\fP \fBipv4_is_local_multicast\fP (__be32 \fBaddr\fP)"
.br
.ti -1c
.RI "static \fBbool\fP \fBipv4_is_lbcast\fP (__be32 \fBaddr\fP)"
.br
.ti -1c
.RI "static \fBbool\fP \fBipv4_is_zeronet\fP (__be32 \fBaddr\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static \fBbool\fP ipv4_is_lbcast (__be32 addr)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
44 {
45     /* limited broadcast */
46     return addr == htonl(INADDR_BROADCAST);
47 }
.fi
.SS "static \fBbool\fP ipv4_is_local_multicast (__be32 addr)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
39 {
40     return (addr & htonl(0xffffff00)) == htonl(0xe0000000);
41 }
.fi
.SS "static \fBbool\fP ipv4_is_loopback (__be32 addr)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
29 {
30     return (addr & htonl(0xff000000)) == htonl(0x7f000000);
31 }
.fi
.SS "static \fBbool\fP ipv4_is_multicast (__be32 addr)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
34 {
35     return (addr & htonl(0xf0000000)) == htonl(0xe0000000);
36 }
.fi
.SS "static \fBbool\fP ipv4_is_zeronet (__be32 addr)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
50 {
51     return (addr & htonl(0xff000000)) == htonl(0x00000000);
52 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
