.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/ip_tunnels.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/ip_tunnels.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/version\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBtnl_ptk_info\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBovs_iptunnel_handle_offloads\fP(skb,  csum_help,  gso_type_mask,  fix_segment)   iptunnel_handle_offloads(skb, csum_help, gso_type_mask)"
.br
.ti -1c
.RI "#define \fBTUNNEL_CSUM\fP   __cpu_to_be16(0x01)"
.br
.ti -1c
.RI "#define \fBTUNNEL_ROUTING\fP   __cpu_to_be16(0x02)"
.br
.ti -1c
.RI "#define \fBTUNNEL_KEY\fP   __cpu_to_be16(0x04)"
.br
.ti -1c
.RI "#define \fBTUNNEL_SEQ\fP   __cpu_to_be16(0x08)"
.br
.ti -1c
.RI "#define \fBTUNNEL_STRICT\fP   __cpu_to_be16(0x10)"
.br
.ti -1c
.RI "#define \fBTUNNEL_REC\fP   __cpu_to_be16(0x20)"
.br
.ti -1c
.RI "#define \fBTUNNEL_VERSION\fP   __cpu_to_be16(0x40)"
.br
.ti -1c
.RI "#define \fBTUNNEL_NO_KEY\fP   __cpu_to_be16(0x80)"
.br
.ti -1c
.RI "#define \fBPACKET_RCVD\fP   0"
.br
.ti -1c
.RI "#define \fBPACKET_REJECT\fP   1"
.br
.ti -1c
.RI "#define \fBTUNNEL_DONT_FRAGMENT\fP   __cpu_to_be16(0x0100)"
.br
.ti -1c
.RI "#define \fBTUNNEL_OAM\fP   __cpu_to_be16(0x0200)"
.br
.ti -1c
.RI "#define \fBTUNNEL_CRIT_OPT\fP   __cpu_to_be16(0x0400)"
.br
.ti -1c
.RI "#define \fBTUNNEL_GENEVE_OPT\fP   __cpu_to_be16(0x0800)"
.br
.ti -1c
.RI "#define \fBTUNNEL_VXLAN_OPT\fP   __cpu_to_be16(0x1000)"
.br
.ti -1c
.RI "#define \fBTUNNEL_OPTIONS_PRESENT\fP   (\fBTUNNEL_GENEVE_OPT\fP | \fBTUNNEL_VXLAN_OPT\fP)"
.br
.ti -1c
.RI "#define \fBskb_is_encapsulated\fP   \fBovs_skb_is_encapsulated\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBovs_skb_is_encapsulated\fP (struct sk_buff *skb)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ovs_iptunnel_handle_offloads(skb, csum_help, gso_type_mask, fix_segment)   iptunnel_handle_offloads(skb, csum_help, gso_type_mask)"

.SS "#define PACKET_RCVD   0"

.SS "#define PACKET_REJECT   1"

.SS "#define skb_is_encapsulated   \fBovs_skb_is_encapsulated\fP"

.SS "#define TUNNEL_CRIT_OPT   __cpu_to_be16(0x0400)"

.SS "#define TUNNEL_CSUM   __cpu_to_be16(0x01)"

.SS "#define TUNNEL_DONT_FRAGMENT   __cpu_to_be16(0x0100)"

.SS "#define TUNNEL_GENEVE_OPT   __cpu_to_be16(0x0800)"

.SS "#define TUNNEL_KEY   __cpu_to_be16(0x04)"

.SS "#define TUNNEL_NO_KEY   __cpu_to_be16(0x80)"

.SS "#define TUNNEL_OAM   __cpu_to_be16(0x0200)"

.SS "#define TUNNEL_OPTIONS_PRESENT   (\fBTUNNEL_GENEVE_OPT\fP | \fBTUNNEL_VXLAN_OPT\fP)"

.SS "#define TUNNEL_REC   __cpu_to_be16(0x20)"

.SS "#define TUNNEL_ROUTING   __cpu_to_be16(0x02)"

.SS "#define TUNNEL_SEQ   __cpu_to_be16(0x08)"

.SS "#define TUNNEL_STRICT   __cpu_to_be16(0x10)"

.SS "#define TUNNEL_VERSION   __cpu_to_be16(0x40)"

.SS "#define TUNNEL_VXLAN_OPT   __cpu_to_be16(0x1000)"

.SH "Function Documentation"
.PP 
.SS "\fBbool\fP ovs_skb_is_encapsulated (struct sk_buff * skb)"

.PP
.nf
176 {
177     /* checking for inner protocol should be sufficient on newer kernel, but
178      * old kernel just set encapsulation bit\&.
179      */
180     return ovs_skb_get_inner_protocol(skb) || skb_encapsulation(skb);
181 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
