.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/list.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/list.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBhlist_entry_safe\fP(ptr,  \fBtype\fP,  member)"
.br
.ti -1c
.RI "#define \fBhlist_for_each_entry\fP(pos,  head,  member)"
.br
.ti -1c
.RI "#define \fBhlist_for_each_entry_safe\fP(pos,  n,  head,  member)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define hlist_entry_safe(ptr, \fBtype\fP, member)"
\fBValue:\fP
.PP
.nf
({ typeof(ptr) ____ptr = (ptr); \
     ____ptr ? hlist_entry(____ptr, type, member) : NULL; \
     })
.fi
.SS "#define hlist_for_each_entry(pos, head, member)"
\fBValue:\fP
.PP
.nf
for (pos = hlist_entry_safe((head)->first, typeof(*(pos)), member);\
         pos;                           \
         pos = hlist_entry_safe((pos)->member\&.next, typeof(*(pos)), member))
.fi
.SS "#define hlist_for_each_entry_safe(pos, n, head, member)"
\fBValue:\fP
.PP
.nf
for (pos = hlist_entry_safe((head)->first, typeof(*pos), member);\
         pos && ({ n = pos->member\&.next; 1; });          \
         pos = hlist_entry_safe(n, typeof(*pos), member))
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
