.TH "mask_cache_entry" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mask_cache_entry \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow_table\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBskb_hash\fP"
.br
.ti -1c
.RI "u32 \fBmask_index\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u32 mask_cache_entry::mask_index"

.SS "u32 mask_cache_entry::skb_hash"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
