.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/mpls.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/mpls.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/if_ether\&.h>\fP
.br
\fC#include <linux/netdevice\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBMPLS_HLEN\fP   4"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "static \fBbool\fP \fBeth_p_mpls\fP (__be16 eth_type)"
.br
.ti -1c
.RI "static unsigned char * \fBskb_mpls_header\fP (struct sk_buff *skb)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define MPLS_HLEN   4"

.SH "Function Documentation"
.PP 
.SS "static \fBbool\fP eth_p_mpls (__be16 eth_type)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
23 {
24     return eth_type == htons(ETH_P_MPLS_UC) ||
25         eth_type == htons(ETH_P_MPLS_MC);
26 }
.fi
.SS "static unsigned char* skb_mpls_header (struct sk_buff * skb)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
36 {
37     return skb_mac_header(skb) + skb->mac_len;
38 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
