.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/net_namespace.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/net_namespace.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFINE_COMPAT_PNET_REG_FUNC\fP(TYPE)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFINE_COMPAT_PNET_REG_FUNC(TYPE)"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
