.TH "/home/vladn/git/ovs/datapath/linux/net_namespace.c" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/net_namespace.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/if_vlan\&.h>\fP
.br
\fC#include <linux/netdevice\&.h>\fP
.br
\fC#include <net/net_namespace\&.h>\fP
.br
\fC#include <net/netns/generic\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
