.TH "netdev_vport" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
netdev_vport \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vport-netdev\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct rcu_head \fBrcu\fP"
.br
.ti -1c
.RI "struct net_device * \fBdev\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct net_device* netdev_vport::dev"

.SS "struct rcu_head netdev_vport::rcu"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
