.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/netdev_features.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/netdev_features.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBNETIF_F_GSO_GRE\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_GRE_CSUM\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_IPIP\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_SIT\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_UDP_TUNNEL\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_UDP_TUNNEL_CSUM\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_MPLS\fP   0"
.br
.ti -1c
.RI "#define \fBNETIF_F_GSO_ENCAP_ALL\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define NETIF_F_GSO_ENCAP_ALL"
\fBValue:\fP
.PP
.nf
(NETIF_F_GSO_GRE |            \\
				 NETIF_F_GSO_GRE_CSUM |         \\
				 NETIF_F_GSO_IPIP |         \\
				 NETIF_F_GSO_SIT |          \\
				 NETIF_F_GSO_UDP_TUNNEL |       \\
				 NETIF_F_GSO_UDP_TUNNEL_CSUM |      \\
				 NETIF_F_GSO_MPLS)
.fi
.SS "#define NETIF_F_GSO_GRE   0"

.SS "#define NETIF_F_GSO_GRE_CSUM   0"

.SS "#define NETIF_F_GSO_IPIP   0"

.SS "#define NETIF_F_GSO_MPLS   0"

.SS "#define NETIF_F_GSO_SIT   0"

.SS "#define NETIF_F_GSO_UDP_TUNNEL   0"

.SS "#define NETIF_F_GSO_UDP_TUNNEL_CSUM   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
