.TH "ovs_key_ipv4_tunnel" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_key_ipv4_tunnel \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be64 \fBtun_id\fP"
.br
.ti -1c
.RI "__be32 \fBipv4_src\fP"
.br
.ti -1c
.RI "__be32 \fBipv4_dst\fP"
.br
.ti -1c
.RI "__be16 \fBtun_flags\fP"
.br
.ti -1c
.RI "u8 \fBipv4_tos\fP"
.br
.ti -1c
.RI "u8 \fBipv4_ttl\fP"
.br
.ti -1c
.RI "__be16 \fBtp_src\fP"
.br
.ti -1c
.RI "__be16 \fBtp_dst\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__be32 ovs_key_ipv4_tunnel::ipv4_dst"

.SS "__be32 ovs_key_ipv4_tunnel::ipv4_src"

.SS "u8 ovs_key_ipv4_tunnel::ipv4_tos"

.SS "u8 ovs_key_ipv4_tunnel::ipv4_ttl"

.SS "__be16 ovs_key_ipv4_tunnel::tp_dst"

.SS "__be16 ovs_key_ipv4_tunnel::tp_src"

.SS "__be16 ovs_key_ipv4_tunnel::tun_flags"

.SS "__be64 ovs_key_ipv4_tunnel::tun_id"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
