.TH "ovs_key_ipv6" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_key_ipv6 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBipv6_src\fP [4]"
.br
.ti -1c
.RI "__be32 \fBipv6_dst\fP [4]"
.br
.ti -1c
.RI "__be32 \fBipv6_label\fP"
.br
.ti -1c
.RI "__u8 \fBipv6_proto\fP"
.br
.ti -1c
.RI "__u8 \fBipv6_tclass\fP"
.br
.ti -1c
.RI "__u8 \fBipv6_hlimit\fP"
.br
.ti -1c
.RI "__u8 \fBipv6_frag\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__be32 ovs_key_ipv6::ipv6_dst[4]"

.SS "__u8 ovs_key_ipv6::ipv6_frag"

.SS "__u8 ovs_key_ipv6::ipv6_hlimit"

.SS "__be32 ovs_key_ipv6::ipv6_label"

.SS "__u8 ovs_key_ipv6::ipv6_proto"

.SS "__be32 ovs_key_ipv6::ipv6_src[4]"

.SS "__u8 ovs_key_ipv6::ipv6_tclass"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
