.TH "ovs_action_push_mpls" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_action_push_mpls \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBmpls_lse\fP"
.br
.ti -1c
.RI "__be16 \fBmpls_ethertype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBovs_action_push_mpls\fP - OVS_ACTION_ATTR_PUSH_MPLS action argument\&. : MPLS label stack entry to push\&. : Ethertype to set in the encapsulating ethernet frame\&.
.PP
The only values  should ever be given are ETH_P_MPLS_UC and ETH_P_MPLS_MC, indicating MPLS unicast or multicast\&. Other are rejected\&. 
.SH "Field Documentation"
.PP 
.SS "__be16 ovs_action_push_mpls::mpls_ethertype"

.SS "__be32 ovs_action_push_mpls::mpls_lse"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
