.TH "ovs_flow_stats" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_flow_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__u64 \fBn_packets\fP"
.br
.ti -1c
.RI "__u64 \fBn_bytes\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__u64 ovs_flow_stats::n_bytes"

.SS "__u64 ovs_flow_stats::n_packets"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
