.TH "ovs_dp_megaflow_stats" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_dp_megaflow_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__u64 \fBn_mask_hit\fP"
.br
.ti -1c
.RI "__u32 \fBn_masks\fP"
.br
.ti -1c
.RI "__u32 \fBpad0\fP"
.br
.ti -1c
.RI "__u64 \fBpad1\fP"
.br
.ti -1c
.RI "__u64 \fBpad2\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__u64 ovs_dp_megaflow_stats::n_mask_hit"

.SS "__u32 ovs_dp_megaflow_stats::n_masks"

.SS "__u32 ovs_dp_megaflow_stats::pad0"

.SS "__u64 ovs_dp_megaflow_stats::pad1"

.SS "__u64 ovs_dp_megaflow_stats::pad2"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
