.TH "ovs_action_push_vlan" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_action_push_vlan \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be16 \fBvlan_tpid\fP"
.br
.ti -1c
.RI "__be16 \fBvlan_tci\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBovs_action_push_vlan\fP - OVS_ACTION_ATTR_PUSH_VLAN action argument\&. : Tag protocol identifier (TPID) to push\&. : Tag control identifier (TCI) to push\&. The CFI bit must be set (but it will not be set in the 802\&.1Q header that is pushed)\&.
.PP
The  value is typically ETH_P_8021Q\&. The only acceptable TPID values are those that the kernel module also parses as 802\&.1Q headers, to prevent OVS_ACTION_ATTR_PUSH_VLAN followed by OVS_ACTION_ATTR_POP_VLAN from having surprising results\&. 
.SH "Field Documentation"
.PP 
.SS "__be16 ovs_action_push_vlan::vlan_tci"

.SS "__be16 ovs_action_push_vlan::vlan_tpid"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
