.TH "ovs_key_nd" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_key_nd \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBnd_target\fP [4]"
.br
.ti -1c
.RI "__u8 \fBnd_sll\fP [ETH_ALEN]"
.br
.ti -1c
.RI "__u8 \fBnd_tll\fP [ETH_ALEN]"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__u8 ovs_key_nd::nd_sll[ETH_ALEN]"

.SS "__be32 ovs_key_nd::nd_target[4]"

.SS "__u8 ovs_key_nd::nd_tll[ETH_ALEN]"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
