.TH "ovs_key_ipv4" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_key_ipv4 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBipv4_src\fP"
.br
.ti -1c
.RI "__be32 \fBipv4_dst\fP"
.br
.ti -1c
.RI "__u8 \fBipv4_proto\fP"
.br
.ti -1c
.RI "__u8 \fBipv4_tos\fP"
.br
.ti -1c
.RI "__u8 \fBipv4_ttl\fP"
.br
.ti -1c
.RI "__u8 \fBipv4_frag\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__be32 ovs_key_ipv4::ipv4_dst"

.SS "__u8 ovs_key_ipv4::ipv4_frag"

.SS "__u8 ovs_key_ipv4::ipv4_proto"

.SS "__be32 ovs_key_ipv4::ipv4_src"

.SS "__u8 ovs_key_ipv4::ipv4_tos"

.SS "__u8 ovs_key_ipv4::ipv4_ttl"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
