.TH "ovs_vport_stats" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_vport_stats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__u64 \fBrx_packets\fP"
.br
.ti -1c
.RI "__u64 \fBtx_packets\fP"
.br
.ti -1c
.RI "__u64 \fBrx_bytes\fP"
.br
.ti -1c
.RI "__u64 \fBtx_bytes\fP"
.br
.ti -1c
.RI "__u64 \fBrx_errors\fP"
.br
.ti -1c
.RI "__u64 \fBtx_errors\fP"
.br
.ti -1c
.RI "__u64 \fBrx_dropped\fP"
.br
.ti -1c
.RI "__u64 \fBtx_dropped\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__u64 ovs_vport_stats::rx_bytes"

.SS "__u64 ovs_vport_stats::rx_dropped"

.SS "__u64 ovs_vport_stats::rx_errors"

.SS "__u64 ovs_vport_stats::rx_packets"

.SS "__u64 ovs_vport_stats::tx_bytes"

.SS "__u64 ovs_vport_stats::tx_dropped"

.SS "__u64 ovs_vport_stats::tx_errors"

.SS "__u64 ovs_vport_stats::tx_packets"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
