.TH "ovs_header" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ovs_header \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <openvswitch\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBdp_ifindex\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct \fBovs_header\fP - header for OVS Generic Netlink messages\&. : ifindex of local port for datapath (0 to make a request not specific to a datapath)\&.
.PP
Attributes following the header are specific to a particular OVS Generic Netlink family, but all of the OVS families use this header\&. 
.SH "Field Documentation"
.PP 
.SS "int ovs_header::dp_ifindex"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
