.TH "pcpu_sw_netstats" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
pcpu_sw_netstats \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <netdevice\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u64 \fBrx_packets\fP"
.br
.ti -1c
.RI "u64 \fBrx_bytes\fP"
.br
.ti -1c
.RI "u64 \fBtx_packets\fP"
.br
.ti -1c
.RI "u64 \fBtx_bytes\fP"
.br
.ti -1c
.RI "struct \fBu64_stats_sync\fP \fBsyncp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u64 pcpu_sw_netstats::rx_bytes"

.SS "u64 pcpu_sw_netstats::rx_packets"

.SS "struct \fBu64_stats_sync\fP pcpu_sw_netstats::syncp"

.SS "u64 pcpu_sw_netstats::tx_bytes"

.SS "u64 pcpu_sw_netstats::tx_packets"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
