.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/reciprocal_div.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/reciprocal_div.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/types\&.h>\fP
.br

.SS "Data Structures"

.in +1c
.ti -1c
.RI "struct \fBreciprocal_value\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBreciprocal_value\fP   \fBrpl_reciprocal_value\fP"
.br
.ti -1c
.RI "#define \fBreciprocal_divide\fP   \fBrpl_reciprocal_divide\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBreciprocal_value\fP \fBrpl_reciprocal_value\fP (u32 d)"
.br
.ti -1c
.RI "static u32 \fBrpl_reciprocal_divide\fP (u32 a, struct \fBreciprocal_value\fP R)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define reciprocal_divide   \fBrpl_reciprocal_divide\fP"

.SS "#define \fBreciprocal_value\fP   \fBrpl_reciprocal_value\fP"

.SH "Function Documentation"
.PP 
.SS "static u32 rpl_reciprocal_divide (u32 a, struct \fBreciprocal_value\fP R)\fC [inline]\fP, \fC [static]\fP"

.PP
.nf
32 {
33     u32 t = (u32)(((u64)a * R\&.m) >> 32);
34     return (t + ((a - t) >> R\&.sh1)) >> R\&.sh2;
35 }
.fi
.SS "struct \fBreciprocal_value\fP rpl_reciprocal_value (u32 d)"

.PP
.nf
12 {
13     struct reciprocal_value R;
14     u64 m;
15     int l;
16 
17     l = fls(d - 1);
18     m = ((1ULL << 32) * ((1ULL << l) - d));
19     do_div(m, d);
20     ++m;
21     R\&.m = (u32)m;
22     R\&.sh1 = min(l, 1);
23     R\&.sh2 = max(l - 1, 0);
24 
25     return R;
26 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
