.TH "reciprocal_value" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
reciprocal_value \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reciprocal_div\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBm\fP"
.br
.ti -1c
.RI "u8 \fBsh1\fP"
.br
.ti -1c
.RI "u8 \fBsh2\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u32 reciprocal_value::m"

.SS "u8 reciprocal_value::sh1"

.SS "u8 reciprocal_value::sh2"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
