.TH "/home/vladn/git/ovs/datapath/linux/compat/include/net/sock.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/net/sock.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB__sk_user_data\fP(sk)   ((*((void \fB__rcu\fP **)&(sk)->sk_user_data)))"
.br
.ti -1c
.RI "#define \fBrcu_dereference_sk_user_data\fP(sk)   rcu_dereference(\fB__sk_user_data\fP((sk)))"
.br
.ti -1c
.RI "#define \fBrcu_assign_sk_user_data\fP(sk,  ptr)   rcu_assign_pointer(\fB__sk_user_data\fP((sk)), ptr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define __sk_user_data(sk)   ((*((void \fB__rcu\fP **)&(sk)->sk_user_data)))"

.SS "#define rcu_assign_sk_user_data(sk, ptr)   rcu_assign_pointer(\fB__sk_user_data\fP((sk)), ptr)"

.SS "#define rcu_dereference_sk_user_data(sk)   rcu_dereference(\fB__sk_user_data\fP((sk)))"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
