.TH "sw_flow_match" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sw_flow_match \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBsw_flow_key\fP * \fBkey\fP"
.br
.ti -1c
.RI "struct \fBsw_flow_key_range\fP \fBrange\fP"
.br
.ti -1c
.RI "struct \fBsw_flow_mask\fP * \fBmask\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct \fBsw_flow_key\fP* sw_flow_match::key"

.SS "struct \fBsw_flow_mask\fP* sw_flow_match::mask"

.SS "struct \fBsw_flow_key_range\fP sw_flow_match::range"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
