.TH "sw_flow_id" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sw_flow_id \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "u32 \fBufid_len\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   u32 \fBufid\fP [\fBMAX_UFID_LENGTH\fP/4]"
.br
.ti -1c
.RI "   struct \fBsw_flow_key\fP * \fBunmasked_key\fP"
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "u32 sw_flow_id::ufid[\fBMAX_UFID_LENGTH\fP/4]"

.SS "u32 sw_flow_id::ufid_len"

.SS "struct \fBsw_flow_key\fP* sw_flow_id::unmasked_key"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
