.TH "table_instance" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
table_instance \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <flow_table\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct flex_array * \fBbuckets\fP"
.br
.ti -1c
.RI "unsigned int \fBn_buckets\fP"
.br
.ti -1c
.RI "struct rcu_head \fBrcu\fP"
.br
.ti -1c
.RI "int \fBnode_ver\fP"
.br
.ti -1c
.RI "u32 \fBhash_seed\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBkeep_flows\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "struct flex_array* table_instance::buckets"

.SS "u32 table_instance::hash_seed"

.SS "\fBbool\fP table_instance::keep_flows"

.SS "unsigned int table_instance::n_buckets"

.SS "int table_instance::node_ver"

.SS "struct rcu_head table_instance::rcu"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
