.TH "/home/vladn/git/ovs/datapath/linux/compat/include/linux/types.h" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/compat/include/linux/types.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef __u16 __bitwise \fB__sum16\fP"
.br
.ti -1c
.RI "typedef __u32 __bitwise \fB__wsum\fP"
.br
.ti -1c
.RI "typedef _Bool \fBbool\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef __u16 __bitwise \fB__sum16\fP"

.SS "typedef __u32 __bitwise \fB__wsum\fP"

.SS "typedef _Bool \fBbool\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
