.TH "/home/vladn/git/ovs/datapath/linux/vport-vxlan.mod.c" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/vladn/git/ovs/datapath/linux/vport-vxlan.mod.c \- 
.SH SYNOPSIS
.br
.PP
\fC#include <linux/module\&.h>\fP
.br
\fC#include <linux/vermagic\&.h>\fP
.br
\fC#include <linux/compiler\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBMODULE_INFO\fP (vermagic, VERMAGIC_STRING)"
.br
.ti -1c
.RI "__visible struct module __this_module \fB__attribute__\fP ((section('\&.gnu\&.linkonce\&.this_module')))"
.br
.ti -1c
.RI "static const struct modversion_info ____versions[] __used \fB__attribute__\fP ((section('__versions')))"
.br
.ti -1c
.RI "static const char __module_depends[] __used \fB__attribute__\fP ((section('\&.modinfo')))"
.br
.ti -1c
.RI "\fBMODULE_INFO\fP (srcversion,'6E49FC69118A97855434D3D')"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "__visible struct module __this_module __attribute__ ((section('\&.gnu\&.linkonce\&.this_module')))"

.SS "static const struct modversion_info ____versions [] __used __attribute__ ((section('__versions')))\fC [static]\fP"

.SS "static const char __module_depends [] __used __attribute__ ((section('\&.modinfo')))\fC [static]\fP"

.SS "MODULE_INFO (vermagic, VERMAGIC_STRING)"

.SS "MODULE_INFO (srcversion, '6E49FC69118A97855434D3D')"

.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
