.TH "vport" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vport \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vport\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct rcu_head \fBrcu\fP"
.br
.ti -1c
.RI "struct \fBdatapath\fP * \fBdp\fP"
.br
.ti -1c
.RI "struct \fBvport_portids\fP \fB__rcu\fP * \fBupcall_portids\fP"
.br
.ti -1c
.RI "u16 \fBport_no\fP"
.br
.ti -1c
.RI "struct hlist_node \fBhash_node\fP"
.br
.ti -1c
.RI "struct hlist_node \fBdp_hash_node\fP"
.br
.ti -1c
.RI "const struct \fBvport_ops\fP * \fBops\fP"
.br
.ti -1c
.RI "struct \fBpcpu_sw_netstats\fP \fB__percpu\fP * \fBpercpu_stats\fP"
.br
.ti -1c
.RI "struct \fBvport_err_stats\fP \fBerr_stats\fP"
.br
.ti -1c
.RI "struct list_head \fBdetach_list\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
struct vport - one port within a datapath : RCU callback head for deferred destruction\&. : Datapath to which this port belongs\&. : RCU protected 'struct \fBvport_portids\fP'\&. : Index into 's  array\&. : Element in  hash table in vport\&.c\&. : Element in ->ports hash table in datapath\&.c\&. : Class structure\&. : Points to per-CPU statistics used and maintained by vport : Points to error statistics used and maintained by vport : list used for detaching vport in net-exit call\&. 
.SH "Field Documentation"
.PP 
.SS "struct list_head vport::detach_list"

.SS "struct \fBdatapath\fP* vport::dp"

.SS "struct hlist_node vport::dp_hash_node"

.SS "struct \fBvport_err_stats\fP vport::err_stats"

.SS "struct hlist_node vport::hash_node"

.SS "const struct \fBvport_ops\fP* vport::ops"

.SS "struct \fBpcpu_sw_netstats\fP \fB__percpu\fP* vport::percpu_stats"

.SS "u16 vport::port_no"

.SS "struct rcu_head vport::rcu"

.SS "struct \fBvport_portids\fP \fB__rcu\fP* vport::upcall_portids"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
