.TH "vxlan_metadata" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vxlan_metadata \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vxlan\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBvni\fP"
.br
.ti -1c
.RI "u32 \fBgbp\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u32 vxlan_metadata::gbp"

.SS "__be32 vxlan_metadata::vni"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
