.TH "vxlanhdr" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vxlanhdr \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "__be32 \fBvx_flags\fP"
.br
.ti -1c
.RI "__be32 \fBvx_vni\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "__be32 vxlanhdr::vx_flags"

.SS "__be32 vxlanhdr::vx_vni"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
