.TH "vxlan_port" 3 "Mon Aug 17 2015" "ovs datapath" \" -*- nroff -*-
.ad l
.nh
.SH NAME
vxlan_port \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "struct \fBvxlan_sock\fP * \fBvs\fP"
.br
.ti -1c
.RI "char \fBname\fP [IFNAMSIZ]"
.br
.ti -1c
.RI "u32 \fBexts\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "u32 vxlan_port::exts"

.SS "char vxlan_port::name"

.SS "struct \fBvxlan_sock\fP * vxlan_port::vs"


.SH "Author"
.PP 
Generated automatically by Doxygen for ovs datapath from the source code\&.
