#!/bin/bash

#fnum=0

#perl -i -wpe 'BEGIN{undef $/} s!/\*.*?\*/!!sg'
#awk -vRS='*/' '{ gsub(/\/\*.*/,"")}1' 
#gawk -vRS='*/' '{ gsub(/\/\*.*/,"")}1'

#[ $# -eq 2 ] && arg="$1" || arg=""
#eval file="\$$#"
#sed 's/a/aA/g;s/__/aB/g;s/#/aC/g' "$file" |
#          gcc -P -E $arg - |
#          sed 's/aC/#/g;s/aB/__/g;s/aA/a/g' 

#sed '/[^\*\/]$/{N;s,^+\\\* .*,+ \/\* Comment removed,;}'
#sed -e '/[^\*\/]$/{N;s,^+ \* .*,+ \* Comment removed,;}' 
#sed -e 's/\/\*.*\*\///g'

#sed '1,/\/\*/!{ \/\*///,/\/\*/!s/^/>>/; }' t2.c

cpp -x c -nostdinc -fdirectives-only
sed 's/^\n//g' t2.c
